services:
  app:
    build:
      context: .
    ports:
      - "5555:7000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      sh -c "npm start"

  db:
    image: mongo
    ports:
      - "1234:27017"
    env_file:
      - .env.db
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro